// <auto-generated />
namespace DoktorMvcProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Doctor_V2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Doctor_V2));
        
        string IMigrationMetadata.Id
        {
            get { return "202003232127456_Doctor_V2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
